server:
  port: 8080
  servlet:
    context-path: /spring-cloud-demo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudlearn
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    com: debug